#ifndef IRC_PROTOCOLE_RULES_HPP
	#define IRC_PROTOCOLE_RULES_HPP

// MESSAGES
#define END_MSG "\r\n"
#define MSG_MAX_SIZE 510


// CHANNEL
#define CHAN_NAME_MAX_SIZE 200
#define CHAN_NAME_FORBID_SPACE " "
#define CHAN_NAME_FORBID_COMMA ","
#define CHAN_NAME_FORBID_CTRLG "\a"

#endif